openshift/cli-manager

- Makefile
- PROJECT
- README.md
- config/default/kustomization.yaml
- config/manager/manager.yaml
- config/manifests/kustomization.yaml
- config/prometheus/monitor.yaml
- config/rbac/auth_proxy_client_clusterrole.yaml
- config/rbac/auth_proxy_role.yaml
- config/rbac/auth_proxy_role_binding.yaml
- config/rbac/auth_proxy_service.yaml
- config/rbac/leader_election_role.yaml
- config/rbac/leader_election_role_binding.yaml
- config/rbac/plugin_editor_role.yaml
- config/rbac/plugin_viewer_role.yaml
- config/rbac/role_binding.yaml
- config/rbac/service_account.yaml
- config/samples/config_v1_plugin.yaml
- controllers/plugin_controller.go
- controllers/suite_test.go
- go.mod
- main.go
- pkg/server/server.go
- pkg/server/server_test.go
- pkg/server/v1/plugins.go
- pkg/server/v1/v1.go
/hold
So we can wire up the CI
> Rename github.com/deejross/openshift-cli-manager to github.com/openshift/cli-manager

- README.md
- pkg/git/git.go
This PR fixes a sha256 mismatch error. Besides, updates README by
adding sections about the configuring CLI Manager on local
> Fix sha256 checksum bug and update README

- pkg/controller/controller.go
Most of the OCP based cli tools are stored in catalog as images and users can easily use them by using the secrets served in there. But catalog serves secrets in dockerconfigjson format and this PR adds support of this.
> NO-JIRA: Add dockerconfigjson support for image pull authentication

- Dockerfile
- Dockerfile.ci
> WRKLDS-1296: Run with non-root user and copy LICENSE

- test/e2e/bindata/assets/02_clusterrole.yaml
[WRKLDS-1287](https://issues.redhat.com/browse/WRKLDS-1287)
> WRKLDS-1287: Replace wildcards with an explicit list of verbs

- .tekton/cli-manager-pull-request.yaml
- .tekton/cli-manager-push.yaml
This PR fixes some other violations that Konflux errors out and prevents new release.
> WRKLDS-1309: Fix some other violations that prevents new release in Konflux

- .tekton/cli-manager-pull-request.yaml
- .tekton/cli-manager-push.yaml
> WRKLDS-1309: Run prefetch-dependencies task even hermetic is true

- Dockerfile
- Dockerfile.ci
> WRKLDS-1372: Update CLI Manager dockerfile component description

- pkg/cmd/cli-manager/cli_manager.go
SDL recommends to add timeout values and max header size limitations in Git http server of cli manager. 
This PR defines:
* 5 min read timeout 
* 15 min write timeout
* 1 MB max header size 
Timeout values are relatively longer because we'll serve binaries via this http and users should have an option to install large binaries. 1 MB max header size should be reasonable as well. However, in case these limitations will not suffice, we may need to increase them.
> WRKLDS-1372: Fine tune Git Http by adding timeout and limit max sizes

- README.md
This PR applies a dummy change to trigger Konflux build for cli-manager.
> NO-JIRA: Add dummy change to trigger Konflux build

- pkg/git/git.go
Per SDL elements recommendation.
> WRKLDS-1348: Add constraint for name and platform input sizes

- .tekton/cli-manager-pull-request.yaml
- .tekton/cli-manager-push.yaml
- renovate.json
Renovate opens numerous PRs periodically and this is distracting. This PR adds renovate.json to only allow the renovate PRs being opened on Tuesday in each week.
> WRKLDS-1421: Add renovate.json to reduce the renovate PRs

- pkg/controller/controller.go
- pkg/version/version.go
> WRKLDS-1421: Fix incorrect texts

- Dockerfile
This PR adds the commit https://github.com/openshift/cli-manager/pull/98/commits/52558c956a32c94317b8037672450d2671093a6d in release-4.17 branch into the main branch in order to stay in sync.
> WRKLDS-1421: Add required labels in dockerfile

- .tekton/cli-manager-pull-request.yaml
- .tekton/cli-manager-push.yaml
- Makefile
> WRKLDS-1421: Add strictfipsruntime tag in go build

- .tekton/cli-manager-4-17-pull-request.yaml
- .tekton/cli-manager-4-17-push.yaml
- Makefile
Manual backport of https://github.com/openshift/cli-manager/pull/107
> [release-4.17] WRKLDS-1421: Add strictfipsruntime tag in go build

- .tekton/cli-manager-pull-request.yaml
- .tekton/cli-manager-push.yaml
> WRKLDS-1421: Remove deprecated sbom-json-check task from tekton pipelines

- Dockerfile
- Makefile
> WRKLDS-1421: Add commit in version tag and use latest 9.4 rhel image

- test/e2e/bindata/assets/04_deployment.yaml
> OCPBUGS-41512: Set readOnlyRootFilesystem to true

- .tekton/cli-manager-pull-request.yaml
- .tekton/cli-manager-push.yaml
This PR adds multi arch image build by configuring the tekton files and changing the pipeline.
> WRKLDS-1491: Add multi arch support for cli manager

- pkg/controller/controller.go
This PR extracts binaries compatible with darwin and windows operating systems from linux/amd64 images in addition to validations for platform string.
> OCPBUGS-43549: Exract darwin/windows binaries from linux/amd64

- README.md
- pkg/git/git.go
> NO-JIRA: Make minor change

- .ci-operator.yaml
- Dockerfile.ci
- Makefile
> NO-JIRA: Fix image references to 4.19

- .tekton/cli-manager-4-18-pull-request.yaml
- .tekton/cli-manager-4-18-push.yaml
> NO-JIRA: Use suggested image url as output

- go.mod
- go.sum
- vendor/golang.org/x/net/http2/client_conn_pool.go
- vendor/golang.org/x/net/http2/config.go
- vendor/golang.org/x/net/http2/config_go124.go
- vendor/golang.org/x/net/http2/config_pre_go124.go
- vendor/golang.org/x/net/http2/frame.go
- vendor/golang.org/x/net/http2/http2.go
- vendor/golang.org/x/net/http2/server.go
- vendor/golang.org/x/net/http2/transport.go
- vendor/golang.org/x/net/http2/unencrypted.go
- vendor/golang.org/x/net/http2/write.go
- vendor/golang.org/x/net/websocket/websocket.go
- vendor/modules.txt
> NO-JIRA: Bump go x/net to 1.33

- Makefile
- renovate.json
> Update renovate schedule to Saturday

- .tekton/cli-manager-4-18-pull-request.yaml
- .tekton/cli-manager-4-18-push.yaml
> Add component name as a subpath in image url

- Makefile
> NO-JIRA: Use 1.0.0 version correctly

- pkg/cmd/cli-manager/cli_manager.go
> NO-JIRA: Add godoc to trigger new build

- renovate.json
> NO-JIRA: [release-4.18]: Disable renovate auto go module updates

- Makefile
> NO-JIRA: Prepare release 0.1.1

- .tekton/cli-manager-pull-request.yaml
- .tekton/cli-manager-push.yaml
> WRKLDS-1662: Add new required tasks

- .tekton/cli-manager-4-18-pull-request.yaml
- .tekton/cli-manager-4-18-push.yaml
> Trigger new release for cli manager

- .tekton/cli-manager-4-18-pull-request.yaml
- .tekton/cli-manager-4-18-push.yaml
> Revert back to working tekton configurations

- .tekton/cli-manager-pull-request.yaml
- .tekton/cli-manager-push.yaml
> NO-JIRA: Add required sast tasks

- .tekton/cli-manager-pull-request.yaml
- .tekton/cli-manager-push.yaml
This PR reacts to changes brought in https://github.com/openshift/cli-manager/pull/283
> NO-JIRA: React to changes in apply-tags
